// This file is part of MicropolisJ.
// Copyright (C) 2013 Jason Long
// Portions Copyright (C) 1989-2007 Electronic Arts Inc.
//
// MicropolisJ is free software; you can redistribute it and/or modify
// it under the terms of the GNU GPLv3, with additional terms.
// See the README file, included in this distribution, for details.

package micropolisj.engine;

/**
 * Enumeration of every possible message for the user generated by the game engine.
 */
public enum MicropolisMessage
{
	//orig_num        generated       last tested/verified
	NEED_RES(false),              //   1            doMessages           1/19
	NEED_COM(false),              //   2            doMessages           1/19
	NEED_IND(false),              //   3            doMessages           1/19
	NEED_ROADS(false),            //   4            doMessages           1/19
	NEED_RAILS(false),            //   5            doMessages           1/20
	NEED_POWER(false),            //   6            doMessages           1/19
	NEED_STADIUM(false),          //   7            doMessages           1/20
	NEED_SEAPORT(false),          //   8            doMessages           1/20
	NEED_AIRPORT(false),          //   9            doMessages
	HIGH_POLLUTION(true),        //  10            doMessages           1/20
	HIGH_CRIME(true),            //  11            doMessages           1/19
	HIGH_TRAFFIC(false),          //  12            doMessages           1/20
	NEED_FIRESTATION(false),      //  13            doMessages           1/19
	NEED_POLICE(false),           //  14            doMessages           1/19
	BLACKOUTS(false),             //  15            doMessages           1/19
	HIGH_TAXES(false),            //  16            doMessages           1/19
	ROADS_NEED_FUNDING(false),    //  17            doMessages
	FIRE_NEED_FUNDING(false),     //  18            doMessages
	POLICE_NEED_FUNDING(false),   //  19            doMessages
	FIRE_REPORT(true),           //  20
	MONSTER_REPORT(true),
	TORNADO_REPORT(true),
	EARTHQUAKE_REPORT(false),     //  23            makeEarthquake
	PLANECRASH_REPORT(true),
	SHIPWRECK_REPORT(true),
	TRAIN_CRASH_REPORT(true),
	COPTER_CRASH_REPORT(true),
	HIGH_UNEMPLOYMENT(false),
	OUT_OF_FUNDS_REPORT(false),
	FIREBOMBING_REPORT(false),  //30
	NEED_PARKS(false),
	EXPLOSION_REPORT(false),
	INSUFFICIENT_FUNDS(false),    //  33            MainWindow.applyCurrentTool
	BULLDOZE_FIRST(false),        //  34            MainWindow.applyCurrentTool
	POP_2K_REACHED(true),        //  35            checkGrowth          1/19
	POP_10K_REACHED(true),       //  36            checkGrowth
	POP_50K_REACHED(true),       //  37            checkGrowth
	POP_100K_REACHED(true),      //  38            checkGrowth
	POP_500K_REACHED(true),      //  39            checkGrowth
	BROWNOUTS_REPORT(false),      //  40                                 1/20
	HEAVY_TRAFFIC_REPORT(false),  //  41           HelicopterSprite
	FLOOD_REPORT(true),
	MELTDOWN_REPORT(true),        // 43            doMeltdown
	RIOTING_REPORT(false),

	// added by Jason
	NO_NUCLEAR_PLANTS(false);

	/**
	 * Whether the message should be displayed in the notification pane.
	 */
	private final boolean useNotificationPane;

	MicropolisMessage(boolean useNotificationPane)
	{
		this.useNotificationPane = useNotificationPane;
	}

	public boolean isUseNotificationPane()
	{
		return useNotificationPane;
	}
}
