version: 2
updates:
  - package-ecosystem: maven
    directory: "/"
    schedule:
      interval: daily
    assignees:
      - dheid
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: daily
    assignees:
      - dheid
